# fleet_platform/workers/ansible_tasks.py
"""Celery tasks for Ansible-based node bootstrap."""
import secrets
import tempfile
import uuid as _uuid
from pathlib import Path

import ansible_runner
from sqlalchemy import select

from fleet_platform.core.auth import hash_password
from fleet_platform.core.config import settings
from fleet_platform.db.session import get_sync_db
from fleet_platform.models.node import Node
from fleet_platform.models.platform_setting import PlatformSetting
from fleet_platform.services.ssh_keypair import get_controller_pubkey
from fleet_platform.workers.celery_app import celery_app

_PLAYBOOKS_DIR = Path(__file__).parent.parent.parent / "playbooks"
_DEFAULT_PILLAR_DIR = Path("/srv/salt/pillar")
_DEFAULT_KRI_DIR = Path.home() / ".kri"


def _get_bootstrap_settings(db) -> tuple[str, str, str, str]:
    """Returns (salt_master, ssh_user, ssh_password, controller_pubkey)."""
    from fleet_platform.services.platform_settings_svc import (
        SALT_MASTER, SSH_USERNAME, SSH_PASSWORD,
        CONTROLLER_PUBKEY_PATH, _fernet,
    )

    def _get(key: str) -> str:
        row = db.execute(
            select(PlatformSetting).where(PlatformSetting.key == key)
        ).scalar_one_or_none()
        if row is None:
            return ""
        if row.is_encrypted and row.value:
            return _fernet().decrypt(row.value.encode()).decode()
        return row.value or ""

    salt_master = _get(SALT_MASTER) or "localhost"
    ssh_user = _get(SSH_USERNAME) or "admin"
    ssh_password = _get(SSH_PASSWORD)
    pub_path = _get(CONTROLLER_PUBKEY_PATH) or str(_DEFAULT_KRI_DIR / "id_rsa.pub")
    pubkey = get_controller_pubkey(pub_path) or ""
    return salt_master, ssh_user, ssh_password, pubkey


def _write_pillar_file(
    pillar_dir: str,
    minion_id: str,
    ingest_url: str,
    node_token: str,
) -> None:
    """Write /srv/salt/pillar/<minion_id>.sls and update top.sls."""
    pillar_path = Path(pillar_dir)
    pillar_path.mkdir(parents=True, exist_ok=True)

    sls_content = (
        f"# Auto-generated by kri — do not edit manually\n"
        f"fleet_platform:\n"
        f"  ingest_url: {ingest_url}\n"
        f"  node_token: {node_token}\n"
    )
    (pillar_path / f"{minion_id}.sls").write_text(sls_content)

    top_path = pillar_path / "top.sls"
    if top_path.exists():
        existing = top_path.read_text()
        if minion_id not in existing:
            top_path.write_text(
                existing.rstrip() + f"\n  '{minion_id}':\n    - {minion_id}\n"
            )
    else:
        top_path.write_text(f"base:\n  '{minion_id}':\n    - {minion_id}\n")


@celery_app.task(
    name="fleet_platform.workers.ansible_tasks.bootstrap_node",
    bind=True,
    max_retries=0,
    queue="maintenance",
)
def bootstrap_node(self, node_id: str, target_ip: str) -> dict:
    """Run bootstrap_mac_mini.yml against a single Mac Mini."""
    node_uuid = _uuid.UUID(node_id)

    # 1. Load node and mark as bootstrapping
    with get_sync_db() as db:
        node = db.execute(
            select(Node).where(Node.id == node_uuid)
        ).scalar_one_or_none()
        if not node:
            return {"status": "error", "reason": "node_not_found"}

        node.bootstrap_status = "bootstrapping"
        node.bootstrap_ip = target_ip
        node.bootstrap_error = None
        db.commit()

        salt_master, ssh_user, ssh_password, controller_pubkey = \
            _get_bootstrap_settings(db)

    # 2. Generate fresh node token and write pillar BEFORE Ansible runs
    raw_token = secrets.token_urlsafe(32)
    ingest_url = f"http://{salt_master}:8000/api/v1/ingest"

    _write_pillar_file(
        pillar_dir=str(_DEFAULT_PILLAR_DIR),
        minion_id=node.minion_id,
        ingest_url=ingest_url,
        node_token=raw_token,
    )

    # 3. Update the stored token hash
    with get_sync_db() as db:
        node = db.execute(select(Node).where(Node.id == node_uuid)).scalar_one()
        node.node_token_hash = hash_password(raw_token)
        db.commit()

    # 4. Run Ansible
    with tempfile.TemporaryDirectory(prefix="kri-bootstrap-") as tmpdir:
        result = ansible_runner.run(
            private_data_dir=tmpdir,
            playbook=str(_PLAYBOOKS_DIR / "bootstrap_mac_mini.yml"),
            inventory=str(_PLAYBOOKS_DIR / "inventory" / "dynamic.py"),
            extravars={
                "salt_master_address": salt_master,
                "minion_id": node.minion_id,
                "controller_pubkey": controller_pubkey,
            },
            envvars={
                "TARGET_HOST": target_ip,
                "ANSIBLE_USER": ssh_user,
                "ANSIBLE_PASSWORD": ssh_password,
            },
            quiet=False,
            rotate_artifacts=1,
        )

    # 5. Update bootstrap status
    with get_sync_db() as db:
        node = db.execute(select(Node).where(Node.id == node_uuid)).scalar_one()
        if result.status == "successful" and result.rc == 0:
            node.bootstrap_status = "completed"
            node.bootstrap_error = None
        else:
            node.bootstrap_status = "failed"
            node.bootstrap_error = f"ansible rc={result.rc} status={result.status}"
        db.commit()

    return {"status": result.status, "rc": result.rc, "node_id": node_id}
