# fleet_platform/workers/ansible_tasks.py
"""Celery tasks for Ansible-based node bootstrap."""
import fcntl
import logging
import re
import secrets
import tempfile
import uuid as _uuid
from pathlib import Path

import ansible_runner
from sqlalchemy import select

from fleet_platform.core.auth import hash_password
from fleet_platform.core.config import settings
from fleet_platform.db.session import get_sync_db
from fleet_platform.models.node import Node
from fleet_platform.models.platform_setting import PlatformSetting
from fleet_platform.services.ssh_keypair import get_controller_pubkey
from fleet_platform.workers.celery_app import celery_app

logger = logging.getLogger(__name__)

_PLAYBOOKS_DIR = Path(__file__).parent.parent.parent / "playbooks"
_DEFAULT_PILLAR_DIR = Path("/srv/salt/pillar")
_DEFAULT_KRI_DIR = Path.home() / ".kri"


_MINION_ID_RE = re.compile(r'^[a-zA-Z0-9._-]{1,128}$')


def _validate_minion_id(minion_id: str) -> str:
    """Validate minion ID to prevent path traversal and YAML injection."""
    if not _MINION_ID_RE.match(minion_id):
        raise ValueError(f"Invalid minion ID '{minion_id}': must match [a-zA-Z0-9._-]{{1,128}}")
    return minion_id


def _get_bootstrap_settings(db) -> tuple[str, str, str, str]:
    """Returns (salt_master, ssh_user, ssh_password, controller_pubkey)."""
    from fleet_platform.services.platform_settings_svc import (
        SALT_MASTER, SSH_USERNAME, SSH_PASSWORD,
        CONTROLLER_PUBKEY_PATH, _fernet,
    )

    def _get(key: str) -> str:
        row = db.execute(
            select(PlatformSetting).where(PlatformSetting.key == key)
        ).scalar_one_or_none()
        if row is None:
            return ""
        if row.is_encrypted and row.value:
            return _fernet().decrypt(row.value.encode()).decode()
        return row.value or ""

    salt_master = _get(SALT_MASTER) or "localhost"
    ssh_user = _get(SSH_USERNAME) or "admin"
    ssh_password = _get(SSH_PASSWORD)
    pub_path = _get(CONTROLLER_PUBKEY_PATH) or str(_DEFAULT_KRI_DIR / "id_rsa.pub")
    pubkey = get_controller_pubkey(pub_path) or ""
    return salt_master, ssh_user, ssh_password, pubkey


def _get_pillar_dir(db) -> Path:
    """Return the configured pillar directory, falling back to /srv/salt/pillar."""
    from fleet_platform.models.platform_setting import PlatformSetting
    from sqlalchemy import select as _select
    row = db.execute(
        _select(PlatformSetting).where(PlatformSetting.key == "pillar_dir")
    ).scalar_one_or_none()
    if row and row.value:
        return Path(row.value)
    return _DEFAULT_PILLAR_DIR


def _write_pillar_file(
    pillar_dir: str,
    minion_id: str,
    ingest_url: str,
    node_token: str,
) -> None:
    """Write /srv/salt/pillar/<minion_id>.sls and update top.sls."""
    _validate_minion_id(minion_id)  # raises ValueError on invalid input
    pillar_path = Path(pillar_dir)
    pillar_path.mkdir(parents=True, exist_ok=True)

    sls_content = (
        f"# Auto-generated by kri — do not edit manually\n"
        f"fleet_platform:\n"
        f"  ingest_url: {ingest_url}\n"
        f"  node_token: {node_token}\n"
    )
    (pillar_path / f"{minion_id}.sls").write_text(sls_content)

    top_path = pillar_path / "top.sls"
    lock_path = pillar_path / ".top.sls.lock"
    with open(lock_path, "w") as lock_f:
        fcntl.flock(lock_f, fcntl.LOCK_EX)
        try:
            if top_path.exists():
                existing = top_path.read_text()
                if minion_id not in existing:
                    top_path.write_text(
                        existing.rstrip() + f"\n  '{minion_id}':\n    - {minion_id}\n"
                    )
            else:
                top_path.write_text(f"base:\n  '{minion_id}':\n    - {minion_id}\n")
        finally:
            fcntl.flock(lock_f, fcntl.LOCK_UN)


@celery_app.task(
    name="fleet_platform.workers.ansible_tasks.bootstrap_node",
    bind=True,
    max_retries=0,
    queue="maintenance",
)
def bootstrap_node(self, node_id: str, target_ip: str) -> dict:
    """Run bootstrap_mac_mini.yml against a single Mac Mini."""
    node_uuid = _uuid.UUID(node_id)
    logger.info("bootstrap_node starting: node_id=%s target_ip=%s", node_id, target_ip)

    # 1. Load node and mark as bootstrapping
    with get_sync_db() as db:
        node = db.execute(
            select(Node).where(Node.id == node_uuid)
        ).scalar_one_or_none()
        if not node:
            return {"status": "error", "reason": "node_not_found"}
        try:
            _validate_minion_id(node.minion_id)
        except ValueError as e:
            node.bootstrap_status = "failed"
            node.bootstrap_error = str(e)
            db.commit()
            return {"status": "error", "reason": str(e)}

        node.bootstrap_status = "bootstrapping"
        node.bootstrap_ip = target_ip
        node.bootstrap_error = None
        db.commit()

        salt_master, ssh_user, ssh_password, controller_pubkey = \
            _get_bootstrap_settings(db)
        pillar_dir = _get_pillar_dir(db)

        if not ssh_password:
            logger.warning(
                "bootstrap_node: SSH password missing from settings for node_id=%s", node_id
            )

    # 2. Generate fresh node token and write pillar BEFORE Ansible runs
    raw_token = secrets.token_urlsafe(32)
    ingest_url = f"http://{salt_master}:8000/api/v1/ingest"

    if not pillar_dir.is_dir() or not _pillar_dir_writable(pillar_dir):
        logger.warning(
            "bootstrap_node: pillar dir %s is not writable for node_id=%s", pillar_dir, node_id
        )

    _write_pillar_file(
        pillar_dir=str(pillar_dir),
        minion_id=node.minion_id,
        ingest_url=ingest_url,
        node_token=raw_token,
    )
    logger.info(
        "bootstrap_node: pillar written for minion_id=%s node_id=%s", node.minion_id, node_id
    )

    # 3. Update the stored token hash
    with get_sync_db() as db:
        node = db.execute(select(Node).where(Node.id == node_uuid)).scalar_one()
        node.node_token_hash = hash_password(raw_token)
        db.commit()

    # 4. Run Ansible with static inventory and capture stdout
    stdout_lines: list[str] = []
    last_task: str = ""
    node_minion_id = node.minion_id  # capture before context closes

    logger.info("bootstrap_node: starting ansible-runner for node_id=%s", node_id)

    with tempfile.TemporaryDirectory(prefix="kri-bootstrap-") as tmpdir:
        # Write static inventory — more reliable than dynamic.py (env var propagation issues)
        inv_path = Path(tmpdir) / "inventory.ini"
        inv_path.write_text(
            f"[targets]\n"
            f"{target_ip} ansible_host={target_ip} "
            f"ansible_user={ssh_user} ansible_ssh_pass={ssh_password} "
            f"ansible_become_password={ssh_password}\n"
        )
        inv_path.chmod(0o600)

        result = ansible_runner.run(
            private_data_dir=tmpdir,
            playbook=str(_PLAYBOOKS_DIR / "bootstrap_mac_mini.yml"),
            inventory=str(inv_path),
            extravars={
                "salt_master_address": salt_master,
                "minion_id": node_minion_id,
                "controller_pubkey": controller_pubkey,
            },
            envvars={
                "ANSIBLE_COLLECTIONS_PATH": str(_PLAYBOOKS_DIR / "collections" / "installed"),
                # -F /dev/null skips ~/.ssh/config entirely — required when the config
                # file is bind-mounted from the host with wrong ownership (UID mismatch
                # between host user and container root causes "Bad owner or permissions")
                "ANSIBLE_SSH_ARGS": "-F /dev/null -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null",
            },
            quiet=False,
            rotate_artifacts=1,
            timeout=1200,  # 20-minute hard timeout
        )
        for event in result.events:
            event_type = event.get("event", "")
            logger.debug("bootstrap_node: ansible event type=%s node_id=%s", event_type, node_id)

            # Track last executing task name for progress + failure diagnostics
            if event_type in ("runner_on_start", "playbook_on_task_start"):
                event_data = event.get("event_data", {})
                task_name = event_data.get("task", "") or event_data.get("task_path", "")
                if task_name:
                    last_task = task_name
                    # Write live progress into bootstrap_error while still bootstrapping
                    # (no bootstrap_last_task column on model — embed in bootstrap_error)
                    with get_sync_db() as _db:
                        _node = _db.execute(
                            select(Node).where(Node.id == node_uuid)
                        ).scalar_one_or_none()
                        if _node and _node.bootstrap_status == "bootstrapping":
                            _node.bootstrap_error = f"[blocked at: TASK {last_task}]"
                            _db.commit()

            msg = event.get("stdout", "")
            if msg:
                stdout_lines.append(msg)

    # 5. Detect common failure modes from stdout
    full_stdout = "\n".join(stdout_lines)
    bootstrap_error: str | None = None

    if result.status == "timeout":
        bootstrap_error = (
            f"Timed out after 20 minutes. Last task: {last_task}" if last_task
            else "Timed out after 20 minutes."
        )
    elif result.status != "successful" or result.rc != 0:
        if "UNREACHABLE" in full_stdout:
            bootstrap_error = (
                f"SSH unreachable: check IP {target_ip} and SSH credentials in Settings"
            )
        elif "Authentication failure" in full_stdout or "Permission denied" in full_stdout:
            bootstrap_error = (
                "SSH auth failed: check SSH username/password in Settings → Bootstrap"
            )
        elif "No such file or directory" in full_stdout and "salt" in full_stdout:
            bootstrap_error = "Salt package not found on target node"
        elif "Could not match supplied host pattern" in full_stdout:
            bootstrap_error = (
                "Inventory misconfiguration — check minion ID format"
            )
        else:
            bootstrap_error = f"ansible rc={result.rc} status={result.status}"

        logger.error(
            "bootstrap_node: ansible failure rc=%s status=%s last_task=%r node_id=%s",
            result.rc, result.status, last_task, node_id,
        )

    # 6. Update bootstrap status + logs
    with get_sync_db() as db:
        node = db.execute(select(Node).where(Node.id == node_uuid)).scalar_one()
        if result.status == "successful" and result.rc == 0:
            node.bootstrap_status = "completed"
            node.bootstrap_error = None
        else:
            node.bootstrap_status = "failed"
            node.bootstrap_error = bootstrap_error
        node.bootstrap_logs = full_stdout or f"rc={result.rc} status={result.status}"
        db.commit()

    return {"status": result.status, "rc": result.rc, "node_id": node_id}


def _pillar_dir_writable(pillar_dir: Path) -> bool:
    """Return True if pillar_dir exists and is writable by the current process."""
    import os
    return os.access(pillar_dir, os.W_OK)
