# fleet_platform/services/group_secrets_svc.py
"""Service layer for group-scoped Salt pillar secrets."""

import fcntl
import uuid
from pathlib import Path

import yaml
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from fleet_platform.models.group import Group, GroupMember
from fleet_platform.models.group_secret import GroupSecret
from fleet_platform.models.node import Node
from fleet_platform.models.platform_setting import PlatformSetting
from fleet_platform.services.platform_settings_svc import decrypt_secret, encrypt_secret

_DEFAULT_PILLAR_DIR = Path("/srv/salt/pillar")


async def _get_pillar_dir(db: AsyncSession) -> Path:
    row = (await db.execute(select(PlatformSetting).where(PlatformSetting.key == "pillar_dir"))).scalar_one_or_none()
    if row and row.value:
        return Path(row.value)
    return _DEFAULT_PILLAR_DIR


async def get_secrets(db: AsyncSession, group_id: uuid.UUID) -> list[GroupSecret]:
    result = await db.execute(select(GroupSecret).where(GroupSecret.group_id == group_id).order_by(GroupSecret.key))
    return list(result.scalars().all())


async def upsert_secret(
    db: AsyncSession,
    group_id: uuid.UUID,
    key: str,
    plaintext_value: str,
    description: str | None = None,
) -> GroupSecret:
    encrypted = encrypt_secret(plaintext_value)
    result = await db.execute(select(GroupSecret).where(GroupSecret.group_id == group_id, GroupSecret.key == key))
    secret = result.scalar_one_or_none()
    if secret:
        secret.encrypted_value = encrypted
        if description is not None:
            secret.description = description
    else:
        secret = GroupSecret(
            group_id=group_id,
            key=key,
            encrypted_value=encrypted,
            description=description,
        )
        db.add(secret)
    await db.commit()
    await db.refresh(secret)
    return secret


async def delete_secret(db: AsyncSession, group_id: uuid.UUID, key: str) -> bool:
    result = await db.execute(select(GroupSecret).where(GroupSecret.group_id == group_id, GroupSecret.key == key))
    secret = result.scalar_one_or_none()
    if not secret:
        return False
    await db.delete(secret)
    await db.commit()
    return True


async def get_decrypted_secrets(db: AsyncSession, group_id: uuid.UUID) -> dict[str, str]:
    secrets = await get_secrets(db, group_id)
    out: dict[str, str] = {}
    for s in secrets:
        try:
            out[s.key] = decrypt_secret(s.encrypted_value)
        except Exception:
            pass
    return out


async def write_group_pillar(group_id: uuid.UUID, db: AsyncSession) -> None:
    """Write /srv/salt/pillar/group_{group_id}.sls with all group secrets."""
    pillar_dir = await _get_pillar_dir(db)
    sls_path = pillar_dir / f"group_{group_id}.sls"
    lock_path = sls_path.with_suffix(".lock")

    # Fetch secrets before acquiring the lock so DB I/O stays outside the
    # critical section — flock is held only for the file read-modify-write.
    decrypted = await get_decrypted_secrets(db, group_id)

    pillar_dir.mkdir(parents=True, exist_ok=True)
    with open(lock_path, "w") as lock_fh:
        fcntl.flock(lock_fh, fcntl.LOCK_EX)
        sls_path.write_text(
            "# Auto-generated by kri — do not edit manually\n"
            + yaml.dump(decrypted, default_flow_style=False, allow_unicode=True)
        )
        # flock releases automatically when the `with` block exits


async def rebuild_top_sls(db: AsyncSession) -> None:
    """Rewrite /srv/salt/pillar/top.sls with all nodes and group pillars.

    Structure:
      base:
        '*':
          - common          (if a group named 'all' has secrets)
          - group_<id>      (for every group that has at least one secret)
        '<minion_id>':
          - <minion_id>
    """
    pillar_dir = await _get_pillar_dir(db)
    top_path = pillar_dir / "top.sls"
    lock_path = pillar_dir / ".top.sls.lock"

    # Fetch all nodes
    nodes_result = await db.execute(select(Node).order_by(Node.minion_id))
    nodes = list(nodes_result.scalars().all())

    # Fetch all groups that have at least one secret
    groups_result = await db.execute(select(Group).order_by(Group.name))
    groups = list(groups_result.scalars().all())

    # Build per-minion pillar list: {minion_id: [pillar_files]}
    # Start with each minion's own SLS, then append group pillars they belong to.
    minion_pillars: dict[str, list[str]] = {}
    for node in nodes:
        if node.minion_id:
            minion_pillars[node.minion_id] = [node.minion_id]

    # Global groups (all/global/common) → add to '*' so every minion gets them.
    # Non-global groups → only add to their actual members.
    star_entries: list[str] = []

    for g in groups:
        # Check if this group has any secrets at all
        has_secrets = (
            await db.execute(select(GroupSecret).where(GroupSecret.group_id == g.id).limit(1))
        ).scalar_one_or_none() is not None
        if not has_secrets:
            continue

        pillar_ref = "common" if g.name.lower() in ("all", "global", "common") else f"group_{g.id}"

        if g.name.lower() in ("all", "global", "common"):
            star_entries.append(pillar_ref)
        else:
            # Fetch members of this group and add the group pillar only to them
            members_result = await db.execute(select(GroupMember).where(GroupMember.group_id == g.id))
            member_node_ids = {str(m.node_id) for m in members_result.scalars().all()}
            for node in nodes:
                if node.minion_id and str(node.id) in member_node_ids:
                    if node.minion_id not in minion_pillars:
                        minion_pillars[node.minion_id] = [node.minion_id]
                    minion_pillars[node.minion_id].append(pillar_ref)

    pillar_dir.mkdir(parents=True, exist_ok=True)

    # Build YAML manually for exact Salt format
    lines = ["# Auto-generated by kri — do not edit manually", "base:"]
    if star_entries:
        lines.append("  '*':")
        for entry in star_entries:
            lines.append(f"    - {entry}")
    for minion_id, pillar_list in sorted(minion_pillars.items()):
        lines.append(f"  '{minion_id}':")
        for p in pillar_list:
            lines.append(f"    - {p}")
    content = "\n".join(lines) + "\n"

    import fcntl as _fcntl

    with open(lock_path, "w") as lock_f:
        _fcntl.flock(lock_f, _fcntl.LOCK_EX)
        try:
            top_path.write_text(content)
        finally:
            _fcntl.flock(lock_f, _fcntl.LOCK_UN)
