# fleet_platform/services/group_secrets_svc.py
"""Service layer for group-scoped Salt pillar secrets."""
import uuid
from pathlib import Path

import yaml
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from fleet_platform.models.group_secret import GroupSecret
from fleet_platform.models.group import Group
from fleet_platform.models.node import Node
from fleet_platform.models.platform_setting import PlatformSetting
from fleet_platform.services.platform_settings_svc import encrypt_secret, decrypt_secret

_DEFAULT_PILLAR_DIR = Path("/srv/salt/pillar")


async def _get_pillar_dir(db: AsyncSession) -> Path:
    row = (await db.execute(
        select(PlatformSetting).where(PlatformSetting.key == "pillar_dir")
    )).scalar_one_or_none()
    if row and row.value:
        return Path(row.value)
    return _DEFAULT_PILLAR_DIR


async def get_secrets(db: AsyncSession, group_id: uuid.UUID) -> list[GroupSecret]:
    result = await db.execute(
        select(GroupSecret)
        .where(GroupSecret.group_id == group_id)
        .order_by(GroupSecret.key)
    )
    return list(result.scalars().all())


async def upsert_secret(
    db: AsyncSession,
    group_id: uuid.UUID,
    key: str,
    plaintext_value: str,
    description: str | None = None,
) -> GroupSecret:
    encrypted = encrypt_secret(plaintext_value)
    result = await db.execute(
        select(GroupSecret).where(GroupSecret.group_id == group_id, GroupSecret.key == key)
    )
    secret = result.scalar_one_or_none()
    if secret:
        secret.encrypted_value = encrypted
        if description is not None:
            secret.description = description
    else:
        secret = GroupSecret(
            group_id=group_id,
            key=key,
            encrypted_value=encrypted,
            description=description,
        )
        db.add(secret)
    await db.commit()
    await db.refresh(secret)
    return secret


async def delete_secret(db: AsyncSession, group_id: uuid.UUID, key: str) -> bool:
    result = await db.execute(
        select(GroupSecret).where(GroupSecret.group_id == group_id, GroupSecret.key == key)
    )
    secret = result.scalar_one_or_none()
    if not secret:
        return False
    await db.delete(secret)
    await db.commit()
    return True


async def get_decrypted_secrets(db: AsyncSession, group_id: uuid.UUID) -> dict[str, str]:
    secrets = await get_secrets(db, group_id)
    out: dict[str, str] = {}
    for s in secrets:
        try:
            out[s.key] = decrypt_secret(s.encrypted_value)
        except Exception:
            pass
    return out


async def write_group_pillar(group_id: uuid.UUID, db: AsyncSession) -> None:
    """Write /srv/salt/pillar/group_{group_id}.sls with all group secrets."""
    pillar_dir = await _get_pillar_dir(db)
    sls_path = pillar_dir / f"group_{group_id}.sls"

    decrypted = await get_decrypted_secrets(db, group_id)

    pillar_dir.mkdir(parents=True, exist_ok=True)
    sls_path.write_text(
        "# Auto-generated by kri — do not edit manually\n"
        + yaml.dump(decrypted, default_flow_style=False, allow_unicode=True)
    )


async def rebuild_top_sls(db: AsyncSession) -> None:
    """Rewrite /srv/salt/pillar/top.sls with all nodes and group pillars.

    Structure:
      base:
        '*':
          - common          (if a group named 'all' has secrets)
          - group_<id>      (for every group that has at least one secret)
        '<minion_id>':
          - <minion_id>
    """
    pillar_dir = await _get_pillar_dir(db)
    top_path = pillar_dir / "top.sls"
    lock_path = pillar_dir / ".top.sls.lock"

    # Fetch all nodes
    nodes_result = await db.execute(select(Node).order_by(Node.minion_id))
    nodes = list(nodes_result.scalars().all())

    # Fetch all groups that have at least one secret
    groups_result = await db.execute(select(Group).order_by(Group.name))
    groups = list(groups_result.scalars().all())

    groups_with_secrets: list[Group] = []
    for g in groups:
        count_result = await db.execute(
            select(GroupSecret).where(GroupSecret.group_id == g.id).limit(1)
        )
        if count_result.scalar_one_or_none():
            groups_with_secrets.append(g)

    # Build the top.sls structure
    base_section: dict = {}

    # '*' entry for global/common pillars
    star_entries: list[str] = []
    for g in groups_with_secrets:
        if g.name.lower() in ("all", "global", "common"):
            star_entries.append("common")
        else:
            star_entries.append(f"group_{g.id}")
    if star_entries:
        base_section["'*'"] = star_entries

    # Per-minion entries
    for node in nodes:
        if node.minion_id:
            base_section[f"'{node.minion_id}'"] = [node.minion_id]

    pillar_dir.mkdir(parents=True, exist_ok=True)

    # Build YAML manually for exact Salt format
    lines = ["# Auto-generated by kri — do not edit manually", "base:"]
    if "'*'" in base_section:
        lines.append("  '*':")
        for entry in base_section["'*'"]:
            lines.append(f"    - {entry}")
    for node in nodes:
        if node.minion_id:
            lines.append(f"  '{node.minion_id}':")
            lines.append(f"    - {node.minion_id}")
    content = "\n".join(lines) + "\n"

    import fcntl as _fcntl
    with open(lock_path, "w") as lock_f:
        _fcntl.flock(lock_f, _fcntl.LOCK_EX)
        try:
            top_path.write_text(content)
        finally:
            _fcntl.flock(lock_f, _fcntl.LOCK_UN)
