# fleet_platform/services/node_secrets_svc.py
"""Service layer for per-node Salt pillar secrets."""
import fcntl
import uuid
from pathlib import Path

import yaml
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from fleet_platform.models.node_secret import NodeSecret
from fleet_platform.models.platform_setting import PlatformSetting
from fleet_platform.services.platform_settings_svc import decrypt_secret, encrypt_secret

_DEFAULT_PILLAR_DIR = Path("/srv/salt/pillar")


async def _get_pillar_dir(db: AsyncSession) -> Path:
    """Return the configured pillar directory, falling back to /srv/salt/pillar."""
    row = (await db.execute(
        select(PlatformSetting).where(PlatformSetting.key == "pillar_dir")
    )).scalar_one_or_none()
    if row and row.value:
        return Path(row.value)
    return _DEFAULT_PILLAR_DIR


async def get_secrets(db: AsyncSession, node_id: uuid.UUID) -> list[NodeSecret]:
    """Return all NodeSecret rows for the given node (values are still encrypted)."""
    result = await db.execute(
        select(NodeSecret)
        .where(NodeSecret.node_id == node_id)
        .order_by(NodeSecret.key)
    )
    return list(result.scalars().all())


async def upsert_secret(
    db: AsyncSession,
    node_id: uuid.UUID,
    key: str,
    plaintext_value: str,
    description: str | None = None,
) -> NodeSecret:
    """Create or update a secret for the given node. Value is encrypted at rest."""
    encrypted = encrypt_secret(plaintext_value)
    result = await db.execute(
        select(NodeSecret).where(NodeSecret.node_id == node_id, NodeSecret.key == key)
    )
    secret = result.scalar_one_or_none()
    if secret:
        secret.encrypted_value = encrypted
        if description is not None:
            secret.description = description
    else:
        secret = NodeSecret(
            node_id=node_id,
            key=key,
            encrypted_value=encrypted,
            description=description,
        )
        db.add(secret)
    await db.commit()
    await db.refresh(secret)
    return secret


async def delete_secret(db: AsyncSession, node_id: uuid.UUID, key: str) -> bool:
    """Delete a secret. Returns True if it existed."""
    result = await db.execute(
        select(NodeSecret).where(NodeSecret.node_id == node_id, NodeSecret.key == key)
    )
    secret = result.scalar_one_or_none()
    if not secret:
        return False
    await db.delete(secret)
    await db.commit()
    return True


async def get_decrypted_secrets(db: AsyncSession, node_id: uuid.UUID) -> dict[str, str]:
    """Return all secrets as {key: plaintext_value} for pillar injection."""
    secrets = await get_secrets(db, node_id)
    out: dict[str, str] = {}
    for s in secrets:
        try:
            out[s.key] = decrypt_secret(s.encrypted_value)
        except Exception:
            pass
    return out


async def write_node_pillar(node_id: uuid.UUID, minion_id: str, db: AsyncSession) -> None:
    """Merge all node secrets into /srv/salt/pillar/{minion_id}.sls.

    Reads existing pillar content, merges in the new secrets, and writes back.
    The fleet_platform block (node_token, ingest_url) is preserved.
    """
    pillar_dir = await _get_pillar_dir(db)
    sls_path = pillar_dir / f"{minion_id}.sls"
    lock_path = sls_path.with_suffix(".lock")

    # Fetch all decrypted secrets for this node before acquiring the lock so
    # we hold the lock for the shortest possible time (DB I/O is outside it).
    decrypted = await get_decrypted_secrets(db, node_id)

    pillar_dir.mkdir(parents=True, exist_ok=True)
    with open(lock_path, "w") as lock_fh:
        fcntl.flock(lock_fh, fcntl.LOCK_EX)
        # Read existing content if present
        existing: dict = {}
        if sls_path.exists():
            try:
                existing = yaml.safe_load(sls_path.read_text()) or {}
            except Exception:
                existing = {}

        # Merge: preserve existing keys that are not being overwritten by secrets
        merged = dict(existing)
        merged.update(decrypted)

        # Write back as YAML
        sls_path.write_text(
            "# Auto-generated by kri — do not edit manually\n"
            + yaml.dump(merged, default_flow_style=False, allow_unicode=True)
        )
        # flock releases automatically when the `with` block exits
