# Auto-generated audit findings dataset for the kri Fleet Platform.
# Each finding: id, persona, title, severity, location, evidence, impact, recommendation, labels
# severity in {Critical, High, Medium, Low}; labels are GitHub label names.

FINDINGS = []
FINDINGS += [
{
"id": "DEV-1", "persona": "Principal Developer", "severity": "Critical",
"title": "SSH connection cache bypasses authentication for shared (host, port, username) keys",
"location": "fleet_platform/services/ssh_connection_cache.py:61-80; fleet_platform/api/routes/webssh.py:339-356",
"evidence": "key = (host, port, username); if key in _cache: return cached.conn  # returned without any credential check",
"impact": "Cache key omits credentials. If user A opens a key-auth session to node1:22:admin, user B requesting the same (host, port, username) — even with a wrong key/password — receives A's live connection. Authentication is fully bypassed on every cache hit, enabling lateral access to any node another user recently connected to using only the correct username.",
"recommendation": "Include a credential fingerprint in the cache key (HMAC of the public key bytes / KDF of the password) or scope the key to (host, port, username, user_id) so connections are never shared across credentials/users.",
"labels": ["bug", "security"],
},
{
"id": "DEV-2", "persona": "Principal Developer", "severity": "High",
"title": "collect_node_grains reads node token from a pillar file that is never populated (broken since #509)",
"location": "fleet_platform/workers/ansible_tasks.py:882-892",
"evidence": "pillar_file = pillar_dir / f'{minion_id}.sls'; ... if not node_token: return {'status':'error','reason':'no node_token found in pillar'}",
"impact": "Comment at L334 says the local salt-pillar write was removed in #509. The token now lives only in node.node_token_hash, so collect_node_grains (and refresh_all_node_grains) ALWAYS returns an error. Periodic grain refresh is completely broken for every node bootstrapped after #509.",
"recommendation": "Drop the pillar-file lookup; mint a fresh short-lived token per collection (store in node_token_hash) or query the existing node_token_hash and pass it in the ingest request.",
"labels": ["bug"],
},
{
"id": "DEV-3", "persona": "Principal Developer", "severity": "High",
"title": "approve_proposal has no row-level lock; concurrent approvals can double-execute a live tool",
"location": "fleet_platform/services/agent_apply_svc.py:100-128",
"evidence": "if action.status in (...): raise ...; if action.status == 'pending': ... action.status='approved'; await db.commit(); return await _execute(...)  # no SELECT ... FOR UPDATE",
"impact": "Two simultaneous requests with the same approval token both read status=='pending' before either writes; both commit 'approved' and both call _execute, so the tool (e.g. apply_salt_state) runs twice on the fleet. No optimistic/locking guard exists in the approval chain.",
"recommendation": "Use select(PendingAction).where(...).with_for_update() before reading status, or add a version column and catch stale-update conflicts.",
"labels": ["bug"],
},
{
"id": "DEV-4", "persona": "Principal Developer", "severity": "High",
"title": "poll_salt_masters runs asyncio.run() per master in a serial loop",
"location": "fleet_platform/workers/maintenance.py:294-316",
"evidence": "for master in masters: ... result = asyncio.run(run_probe(master))  # new event loop each iteration",
"impact": "Each asyncio.run() builds and tears down an event loop + threadpool; probes run serially. A single hanging probe blocks the whole beat task for its full TCP timeout per master, starving other 30s beat tasks. The sync DB session is also held across all probes.",
"recommendation": "Use a single asyncio.run(asyncio.gather(*[run_probe(m) for m in to_probe])) to probe concurrently, and close the DB session before the async work.",
"labels": ["bug", "refactor"],
},
{
"id": "DEV-5", "persona": "Principal Developer", "severity": "High",
"title": "Sync DB session held open during asyncio.run(run_probe()) network I/O in provision_master",
"location": "fleet_platform/workers/ansible_tasks.py:1288-1293",
"evidence": "with get_sync_db() as _pdb: ... probe_result = dict(asyncio.run(run_probe(_fresh_master)))  # HTTPS calls inside the DB context",
"impact": "A sync connection-pool slot is held while run_probe makes salt-api HTTPS calls (5-30s timeouts). With pool_size=5, a few simultaneous provision completions exhaust the pool and cause 30s timeouts for all other Celery tasks.",
"recommendation": "Read master attributes inside the with-block, exit it, then call asyncio.run(run_probe(...)) outside the DB context.",
"labels": ["bug", "refactor"],
},
{
"id": "DEV-6", "persona": "Principal Developer", "severity": "Medium",
"title": "_check_ingest_rate_limit opens a new Redis client per request and never closes it",
"location": "fleet_platform/api/routes/ingest.py:51-59",
"evidence": "r = sync_redis.Redis.from_url(settings.redis_url, decode_responses=True)  # new pool every call, no close()",
"impact": "Redis.from_url() creates a new connection pool each call on the hot ingest path (up to 60/min per node). At hundreds of nodes this leaks hundreds of pool objects/min, each holding TCP connections to Redis.",
"recommendation": "Use a module-level singleton Redis client, or wrap in `with` + r.close().",
"labels": ["bug"],
},
{
"id": "DEV-7", "persona": "Principal Developer", "severity": "Medium",
"title": "Rate-limiter INCR/EXPIRE are not atomic; TTL can be lost on crash",
"location": "fleet_platform/api/routes/ingest.py:54-56",
"evidence": "count = int(r.incr(key)); if count == 1: r.expire(key, _INGEST_RATE_WINDOW)",
"impact": "If the process dies between INCR and EXPIRE, the key persists without a TTL and the node is permanently rate-limited until manual Redis deletion — a silent operational failure.",
"recommendation": "Use a pipeline (INCR + EXPIRE together) or SET key 0 ex=window nx=True before INCR so the TTL is always set atomically.",
"labels": ["bug"],
},
{
"id": "DEV-8", "persona": "Principal Developer", "severity": "Medium",
"title": "Deprecated asyncio.get_event_loop() used inside coroutines (5 sites)",
"location": "fleet_platform/api/routes/webssh.py:396; api/routes/nodes.py:668; services/alert_svc.py:314; api/routes/platform_settings.py:137; services/monitoring_svc.py:72",
"evidence": "loop = asyncio.get_event_loop()  # deprecated in 3.10+ inside a running coroutine",
"impact": "Emits DeprecationWarning and has subtly different semantics than get_running_loop() in 3.12+; future Python upgrades risk breakage.",
"recommendation": "Replace with asyncio.get_running_loop(), or prefer asyncio.to_thread(...) which is already used correctly elsewhere.",
"labels": ["refactor"],
},
{
"id": "DEV-9", "persona": "Principal Developer", "severity": "Medium",
"title": "SMTP email send failure swallowed silently with no log",
"location": "fleet_platform/services/pending_action_svc.py:156-165 (also node_actions.py:184-187)",
"evidence": "try: ... s.sendmail(...) except Exception: pass",
"impact": "Any SMTP failure (host/TLS/auth/bounce) is discarded with no log line, metric, or Sentry event. Approvers silently never receive approval emails while the action stays pending.",
"recommendation": "Log a warning with exc_info and increment an approval_email_send_failures_total counter.",
"labels": ["bug"],
},
{
"id": "DEV-10", "persona": "Principal Developer", "severity": "Medium",
"title": "create_proposal uses nil UUID as sentinel node_id for multi-target actions",
"location": "fleet_platform/services/agent_apply_svc.py:58-65",
"evidence": "node_id = node.id if node else uuid.UUID(int=0)  # 00000000-0000-0000-0000-000000000000",
"impact": "All multi-target proposals and failed node lookups share the same phantom node_id. Joins to nodes drop or cross-join these rows; a future FK constraint on pending_actions.node_id would reject all existing multi-target rows.",
"recommendation": "Make node_id nullable and use NULL for the no-specific-node case.",
"labels": ["bug"],
},
{
"id": "DEV-11", "persona": "Principal Developer", "severity": "Medium",
"title": "SSH probe writes private key to a temp file without chmod 0600, so OpenSSH rejects it",
"location": "fleet_platform/workers/connectivity_tasks.py:71-88",
"evidence": "with tempfile.NamedTemporaryFile(...) as tmp: tmp.write(ssh_key); tmp.flush(); subprocess.run(['ssh', ..., '-i', tmp.name, ...])  # no chmod",
"impact": "NamedTemporaryFile applies the process umask (often 0644/0640). OpenSSH rejects group/other-readable key files (rc=1), so every key-auth probe falsely classifies the node as unreachable, making reachability data unreliable.",
"recommendation": "Add os.chmod(tmp.name, 0o600) immediately after tmp.flush() and before subprocess.run.",
"labels": ["bug"],
},
{
"id": "DEV-12", "persona": "Principal Developer", "severity": "Low",
"title": "embedding_tasks loads all nodes into memory with an unbounded SELECT",
"location": "fleet_platform/workers/embedding_tasks.py:47",
"evidence": "nodes = (await db.execute(select(Node))).scalars().all()  # no WHERE/LIMIT/streaming",
"impact": "Materializes the entire nodes table (JSONB grains, logs) into a list and keeps all ORM objects in the identity map for the whole loop. At scale this risks OOM-killing the worker and silently cancelling embeddings mid-run.",
"recommendation": "Stream in batches via yield_per() or paginate with LIMIT/OFFSET, flushing each batch.",
"labels": ["refactor"],
},
]
FINDINGS += [
{
"id": "ARC-1", "persona": "Principal Architect", "severity": "Critical",
"title": "Blocking Celery .get() inside an ASGI request handler",
"location": "fleet_platform/api/routes/nodes.py:668-689",
"evidence": "await loop.run_in_executor(None, lambda: salt_run_cmd.delay(...).get(timeout=15))",
"impact": "delay().get() blocks a threadpool thread up to 15s waiting on a Salt round-trip. A handful of concurrent /vms calls starve the uvicorn threadpool and can deadlock if the Celery worker needs a threadpool slot from the same process — the canonical Celery anti-pattern in async services.",
"recommendation": "Return 202 + task_id and poll for status (like POST /salt/cmd), or call the existing sync salt_api_client via asyncio.to_thread instead of round-tripping through Celery.",
"labels": ["bug", "refactor"],
},
{
"id": "ARC-2", "persona": "Principal Architect", "severity": "High",
"title": "Layering violation: service layer imports from the API layer",
"location": "fleet_platform/services/monitoring_svc.py:13",
"evidence": "from fleet_platform.api.deps import get_redis",
"impact": "services/ is below api/ in the intended dependency order. This upward import means the service only works after API lifespan init, can't run from a Celery worker/CLI, and is untestable in isolation.",
"recommendation": "Move Redis client init to fleet_platform/core/redis.py or inject the client as a parameter. Services should depend on core, not on api.",
"labels": ["refactor"],
},
{
"id": "ARC-3", "persona": "Principal Architect", "severity": "High",
"title": "Sync Redis connection created per request on the async ingest hot path",
"location": "fleet_platform/api/routes/ingest.py:49-59",
"evidence": "r = sync_redis.Redis.from_url(settings.redis_url, ...)  # inside async ingest handler; async get_redis() singleton ignored",
"impact": "Each grain push opens a new unpooled TCP connection to Redis with no reuse and no close. A 100-node fleet generates ~100 new connections/min. The async Redis singleton already exists in api/deps.py but is not used here.",
"recommendation": "Use the injected async Redis dependency (await redis.incr/expire) or move the sync call into asyncio.to_thread.",
"labels": ["refactor", "bug"],
},
{
"id": "ARC-4", "persona": "Principal Architect", "severity": "High",
"title": "Deprecated inline SSH credential columns still live and read as fallback (dual secret paths)",
"location": "fleet_platform/models/node.py:51-56; fleet_platform/models/group.py:28-31",
"evidence": "ssh_username/ssh_password_enc/ssh_auth_mode/ssh_key_enc marked DEPRECATED (#704/#697) but still read via services/ssh_credential_link.py; migration 055 exists",
"impact": "Two Fernet-encrypted storage paths run simultaneously for the same secret, so migration 055 can't be verified complete by inspection and a fallback bug can keep decrypting from the deprecated columns even after migration.",
"recommendation": "Finish migration 055, add migration 056 to drop the columns, and remove the fallback read path after the migration window.",
"labels": ["refactor", "security"],
},
{
"id": "ARC-5", "persona": "Principal Architect", "severity": "High",
"title": "Routes import worker modules directly, coupling API and worker import graphs",
"location": "fleet_platform/api/routes/ingest.py:26-27; api/routes/drift.py:18; api/routes/nodes.py:665 (+9 more)",
"evidence": "from fleet_platform.workers.drift_tasks import compute_drift; from fleet_platform.workers.sbom_tasks import index_sbom",
"impact": "Importing worker callables pulls celery_app init, sync DB engines, and HTTP clients into every uvicorn worker. Worker import-time side effects can crash API startup, and the shared import graph blocks independent deploy/scale.",
"recommendation": "Dispatch by string name via celery_app.send_task(...) or behind a service layer; apply deferred local imports consistently.",
"labels": ["refactor"],
},
{
"id": "ARC-6", "persona": "Principal Architect", "severity": "Medium",
"title": "God files: ansible.py (~1,660 lines) and ansible_tasks.py (~1,375 lines)",
"location": "fleet_platform/api/routes/ansible.py; fleet_platform/workers/ansible_tasks.py",
"evidence": "ansible.py mixes git source mgmt, playbook discovery, YAML parsing, subprocess, file browsing, bootstrap, git clone, extravars scrub, audit logging in one router",
"impact": "Untestable in isolation, change-risky, and violates SRP. Pure business logic (_scrub_extravars, _validate_minion_id, _git_clone_and_list) lives in a router file.",
"recommendation": "Split ansible.py into a thin router + services (playbook_source_mgr, bootstrap_svc); split ansible_tasks.py into bootstrap_tasks and grain_tasks.",
"labels": ["refactor"],
},
{
"id": "ARC-7", "persona": "Principal Architect", "severity": "Medium",
"title": "Fernet cipher re-instantiated on every encrypt/decrypt call",
"location": "fleet_platform/services/platform_settings_svc.py:228-234",
"evidence": "def _fernet(): return Fernet(_fernet_key())  # re-derives key + rebuilds Fernet each call",
"impact": "Every node credential read, Salt API password decrypt, and SMTP/LLM secret access re-hashes/decodes the key and rebuilds Fernet. Redundant CPU work under load; the key never changes at runtime.",
"recommendation": "Cache the Fernet instance as a module-level singleton initialized once.",
"labels": ["refactor"],
},
{
"id": "ARC-8", "persona": "Principal Architect", "severity": "Medium",
"title": "Minion-ID validation regex duplicated across 5 files with inconsistent bounds",
"location": "api/routes/fleet.py:40; api/routes/ansible.py:44; api/routes/salt_ops.py:27; api/routes/salt_keys.py:20; workers/ansible_tasks.py:43",
"evidence": "fleet.py/salt_ops.py/salt_keys.py use ^[a-zA-Z0-9._-]+ (no length bound); ansible.py uses ^[a-zA-Z0-9._-]{1,128}$",
"impact": "fleet.py and salt_ops/keys accept arbitrarily long minion IDs; an adversary can submit a 10KB ID that passes one validator but is rejected later — inconsistent validation surfaces.",
"recommendation": "Centralize MINION_ID_RE = re.compile(r'^[a-zA-Z0-9._-]{1,128}$') in core/validators.py and import everywhere.",
"labels": ["refactor", "security"],
},
{
"id": "ARC-9", "persona": "Principal Architect", "severity": "Medium",
"title": "node_facts hypertable has retention but no compression policy",
"location": "fleet_platform/db/migrations/versions/001_initial_schema.py:117",
"evidence": "create_hypertable('node_facts', ...); add_retention_policy('node_facts', INTERVAL '90 days')  # no add_compression_policy, unlike node_health_snapshots",
"impact": "node_facts stores 5-20KB JSONB grain blobs. At ~300 nodes every 5 min that is ~500MB/day uncompressed → ~45GB over 90 days vs ~3-5GB compressed.",
"recommendation": "Add add_compression_policy('node_facts', INTERVAL '7 days') with segmentby='node_id' in a new migration.",
"labels": ["infra"],
},
{
"id": "ARC-10", "persona": "Principal Architect", "severity": "Medium",
"title": "Single Celery Beat is a silent SPOF for all 15 scheduled tasks",
"location": "fleet_platform/workers/celery_app.py:94-188",
"evidence": "15 beats configured on one celery beat process; redbeat_redis_url set but RedBeatScheduler not configured as beat_scheduler",
"impact": "A beat crash silently stops grain refresh, stale-node marking, alert evaluation, and reapers — the system degrades with no alert; /monitoring/summary does not check beat liveness.",
"recommendation": "Enable redbeat as the scheduler for HA, or add a beat heartbeat key + alert when it goes stale.",
"labels": ["infra"],
},
{
"id": "ARC-11", "persona": "Principal Architect", "severity": "Medium",
"title": "Pervasive frontend polling with no push mechanism for live job state",
"location": "frontend/src/pages/PlaybookJobDetail.tsx; pages/BootstrapModal.tsx; lib/bootstrapRefetchInterval.ts (+21 files)",
"evidence": "24 files use refetchInterval/setInterval; SSE infra already exists (POST /api/v1/agent/run/stream, WebSocket in webssh.py) but is unused for jobs",
"impact": "Each open tab issues full authenticated HTTP+DB requests every interval; with N operators watching jobs this becomes the dominant read load and scales linearly with users.",
"recommendation": "Reuse the SSE pattern from agent.py for an /ansible/jobs/{id}/stream endpoint; subscribe once per tab.",
"labels": ["refactor", "frontend"],
},
{
"id": "ARC-12", "persona": "Principal Architect", "severity": "Low",
"title": "All-deprecated X-XSS-Protection header and no API-versioning strategy beyond /api/v1 prefix",
"location": "deploy/nginx.conf.template; fleet_platform/api (route prefixes)",
"evidence": "Routes hardcode /api/v1 prefixes throughout; no documented deprecation/versioning policy for breaking schema changes",
"impact": "Without a versioning/deprecation policy, breaking changes to response schemas affect the SPA and any external consumers with no migration window.",
"recommendation": "Document an API versioning + deprecation policy and add contract tests (see Tester findings) to detect schema drift.",
"labels": ["docs", "refactor"],
},
]
FINDINGS += [
{
"id": "SRE-1", "persona": "Principal SRE", "severity": "Critical",
"title": "Default admin/admin credential documented, not enforced to change",
"location": "README.md:141",
"evidence": "log in with `admin` / `admin` — change this immediately under Settings.",
"impact": "Any operator who follows quick start and forgets to change it exposes full admin control of the fleet plane (SSH keys, node secrets, playbook execution). The advisory text provides no enforcement, and it diverges from the env-var seeding path in user_seeding.py.",
"recommendation": "Eliminate the admin/admin default (require explicit seed env vars) or force a one-time password change on first login; audit deployed instances for the default hash.",
"labels": ["security"],
},
{
"id": "SRE-2", "persona": "Principal SRE", "severity": "High",
"title": "cmd.run in Salt API allowlist grants operator-level RCE on any fleet node",
"location": "deploy/salt-master.conf:83; fleet_platform/services/platform_settings_svc.py:98",
"evidence": "external_auth allowlist includes 'cmd.run'; _DEFAULT_SALT_FUNCTIONS includes it; _FORBIDDEN_SALT_FUNCTIONS only applies to AI-generated artifacts",
"impact": "Any operator-role user can POST /api/v1/salt/cmd {function:'cmd.run', args:['<shell>']} for remote shell on every node. The agent forbidden-function set does not cover direct operator API calls.",
"recommendation": "Remove cmd.run from the Salt external_auth allowlist and _DEFAULT_SALT_FUNCTIONS; if needed, restrict to admin role behind a separate approval + audit workflow.",
"labels": ["security"],
},
{
"id": "SRE-3", "persona": "Principal SRE", "severity": "High",
"title": "Login rate limiter keyed on spoofable X-Forwarded-For",
"location": "fleet_platform/api/limiter.py:13; deploy/nginx.conf.template:49",
"evidence": "Limiter(key_func=get_remote_address); nginx uses proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for (appends)",
"impact": "SlowAPI reads the first XFF IP; nginx appends rather than overwrites, so an attacker sending X-Forwarded-For: 1.2.3.4 controls the limiter key and can rotate fake IPs to fully bypass the 10/min login limit — enabling credential brute force.",
"recommendation": "Set proxy_set_header X-Forwarded-For $remote_addr at the nginx boundary and configure SlowAPI with an explicit trusted-proxy list.",
"labels": ["security"],
},
{
"id": "SRE-4", "persona": "Principal SRE", "severity": "High",
"title": "No securityContext in any Kubernetes deployment",
"location": "deploy/k8s/api-deployment.yaml; worker-deployment.yaml; beat-deployment.yaml; worker-ansible-deployment.yaml",
"evidence": "Zero matches for securityContext/runAsNonRoot/allowPrivilegeEscalation/readOnlyRootFilesystem/capabilities across all four manifests",
"impact": "Without runAsNonRoot/allowPrivilegeEscalation:false/drop ALL capabilities, a container exploit can escalate to root; pods would be rejected by Pod Security Admission 'restricted'.",
"recommendation": "Add a hardened pod/container securityContext (runAsNonRoot, runAsUser 1001, allowPrivilegeEscalation:false, readOnlyRootFilesystem, capabilities drop ALL).",
"labels": ["security", "infra"],
},
{
"id": "SRE-5", "persona": "Principal SRE", "severity": "Medium",
"title": "pg_backup container runs as root and has no healthcheck",
"location": "deploy/docker-compose.yml:59-106",
"evidence": "writes creds to /root/.config/rclone/rclone.conf (root); no healthcheck stanza unlike all other services",
"impact": "Root process holds cloud-storage credentials (container breakout = host compromise). Failed backups are silent — restart policy retries but never alerts, so an operator may believe backups run while they have failed for days.",
"recommendation": "Run the backup service non-root, add a healthcheck verifying a recent dump file, and add a dead-man's-switch alert.",
"labels": ["infra", "security"],
},
{
"id": "SRE-6", "persona": "Principal SRE", "severity": "Medium",
"title": "Backups unencrypted and local-only by default",
"location": "deploy/.env.docker.example:60-82; deploy/docker-compose.yml:42,63",
"evidence": "BACKUP_AGE_RECIPIENT defaults empty; 'WARN: age encryption failed, keeping plain dump'; BACKUP_REMOTE also defaults empty",
"impact": "By default a full PostgreSQL dump (hashed passwords, encrypted node/group secrets, audit logs, topology) sits unencrypted on the host volume with no offsite copy. Volume/host theft yields the whole DB.",
"recommendation": "Make BACKUP_AGE_RECIPIENT required in production (${VAR:?}), strongly recommend BACKUP_REMOTE, and warn at startup when neither is set.",
"labels": ["security", "infra"],
},
{
"id": "SRE-7", "persona": "Principal SRE", "severity": "Medium",
"title": "/metrics endpoint unauthenticated at the application layer",
"location": "fleet_platform/api/main.py:194-204",
"evidence": "@app.get('/metrics') ... no Depends(get_current_user); protection delegated entirely to nginx IP ACLs",
"impact": "If the API becomes directly reachable (port-forward, LB misconfig, same Docker network), all metrics — including kri_node_ssh_reachable{minion_id} — are readable without auth.",
"recommendation": "Add a bearer/shared-secret (METRICS_TOKEN) check on the /metrics handler as defense in depth.",
"labels": ["security"],
},
{
"id": "SRE-8", "persona": "Principal SRE", "severity": "Medium",
"title": "auth/refresh endpoint has no rate limit",
"location": "fleet_platform/api/routes/auth.py:73-116",
"evidence": "@router.post('/refresh') has no @limiter.limit(...) unlike /auth/login (10/minute)",
"impact": "An attacker holding a stolen refresh token can mint unlimited access tokens with no throttling.",
"recommendation": "Apply @limiter.limit('20/minute') (or stricter) to /auth/refresh.",
"labels": ["security"],
},
{
"id": "SRE-9", "persona": "Principal SRE", "severity": "Medium",
"title": "FERNET_SECRET_KEY missing from .env.docker.example; CI uses a different name",
"location": "deploy/.env.docker.example (absent); fleet_platform/services/platform_settings_svc.py:210-214",
"evidence": "Non-dev raises RuntimeError if FERNET_SECRET_KEY unset; example file omits it; CI workflow sets FERNET_KEY (different name)",
"impact": "Operators copying the example hit a RuntimeError the first time a secret is read in production. CI's wrong variable name leaves fernet_secret_key=None, masking the issue until prod.",
"recommendation": "Add FERNET_SECRET_KEY to .env.docker.example with generation instructions and fix the CI workflow to use FERNET_SECRET_KEY.",
"labels": ["bug", "docs", "infra"],
},
{
"id": "SRE-10", "persona": "Principal SRE", "severity": "Medium",
"title": "No Content-Security-Policy header; deprecated X-XSS-Protection still set",
"location": "deploy/nginx.conf.template:19-24; deploy/nginx-tls.conf.template:21-26",
"evidence": "Sets X-Content-Type-Options/X-Frame-Options/X-XSS-Protection/Referrer-Policy/Permissions-Policy but no Content-Security-Policy",
"impact": "Without CSP, any reflected/stored XSS in the SPA can exfiltrate JWTs from localStorage and drive fleet-wide API calls.",
"recommendation": "Add a strict CSP (default-src 'self'; script-src 'self'; object-src 'none'; frame-ancestors 'none') and remove the deprecated X-XSS-Protection header.",
"labels": ["security"],
},
{
"id": "SRE-11", "persona": "Principal SRE", "severity": "Medium",
"title": "Ingest rate limiter fails open when Redis is unavailable",
"location": "fleet_platform/api/routes/ingest.py:57-59",
"evidence": "except Exception: return True  # fail open",
"impact": "If Redis is down, the per-node 10/min ingest limit is silently bypassed for all nodes; a compromised/malfunctioning node can flood the API and fill PostgreSQL with process-stat rows.",
"recommendation": "Fail closed (or at minimum emit a kri_ingest_ratelimit_redis_errors_total metric/log) so the outage is visible before it becomes a flood.",
"labels": ["security", "bug"],
},
{
"id": "SRE-12", "persona": "Principal SRE", "severity": "Medium",
"title": "No K8s NetworkPolicy, PodDisruptionBudget, or HPA; all deployments replicas: 1",
"location": "deploy/k8s/ (absent files)",
"evidence": "No networkpolicy.yaml/poddisruptionbudget.yaml/hpa.yaml; all deployments run replicas: 1",
"impact": "Any pod can reach any other (compromised frontend → API internal port); a node drain causes full API outage; no autoscaling under load.",
"recommendation": "Add NetworkPolicy (restrict API ingress to nginx/monitoring), PDBs (minAvailable:1), and HPA for the API.",
"labels": ["infra", "security"],
},
{
"id": "SRE-13", "persona": "Principal SRE", "severity": "Low",
"title": "pg_backup installs age + rclone at runtime (supply-chain + cold-start risk)",
"location": "deploy/docker-compose.yml:62-66",
"evidence": "if ! command -v age ...: apt-get update && apt-get install -y age rclone  # unpinned, every start",
"impact": "Every (re)start fetches unpinned packages from apt mirrors — a compromised mirror or breaking bump silently alters backups; adds ~30s start latency; breaks air-gapped deploys.",
"recommendation": "Build a Dockerfile.backup with pinned age/rclone, run non-root, and scan it with Trivy in CI.",
"labels": ["infra", "security"],
},
]
FINDINGS += [
{
"id": "AI-1", "persona": "Principal AI/LLM Expert", "severity": "High",
"title": "Indirect prompt injection via unsanitized tool-result observations",
"location": "fleet_platform/agent/planner.py:42-56, 79-87",
"evidence": "_summarize_result serializes raw tool result into observations; _user_prompt concatenates them into the next-iteration prompt without sanitization",
"impact": "Tool results include raw DB data (hostnames, minion IDs, playbook/RAG text). Unlike the system prompt (which runs sanitize_untrusted), these observations are injected raw, so a hostile node hostname can steer the model — info exfiltration for read tools and approval-gate social engineering for write tools.",
"recommendation": "Apply sanitize_untrusted (or is_suspicious flagging) to all string values inside tool results before serializing, mirroring llm_context._sanitize_cell.",
"labels": ["security"],
},
{
"id": "AI-2", "persona": "Principal AI/LLM Expert", "severity": "High",
"title": "Operator can self-approve their own agent-proposed actions (single-target)",
"location": "fleet_platform/services/agent_apply_svc.py:107-116",
"evidence": "On the pending→approved path there is no approver_email != action.requested_by check (only the co-sign path enforces a different person); co-sign triggers only above 8 targets",
"impact": "For every single-target live action (restart_service, apply_salt_state, set_pillar, bootstrap_node, enable_node) the human-in-the-loop gate is a rubber stamp the requester can click. A compromised/malicious operator can propose and self-approve destructive actions.",
"recommendation": "Reject approval when approver_email == requested_by on the single-approval path.",
"labels": ["security"],
},
{
"id": "AI-3", "persona": "Principal AI/LLM Expert", "severity": "High",
"title": "set_pillar tool silently ignores its value argument",
"location": "fleet_platform/agent/tools.py:382-392",
"evidence": "_set_pillar only calls saltutil.refresh_pillar(minion_id) then returns {'pillar_key':..., 'value':..., 'refreshed':...} — key/value never applied",
"impact": "Operator/LLM believes a pillar value was set and sees it confirmed in the audit log, but only a refresh ran. Breaks operational intent silently; a secret rotation leaves the old secret active while the audit trail says otherwise.",
"recommendation": "Either remove pillar_key/value from the schema (since unused) or implement actual pillar-value setting and document preconditions.",
"labels": ["bug", "security"],
},
{
"id": "AI-4", "persona": "Principal AI/LLM Expert", "severity": "High",
"title": "RAG chunk content injected raw into the system prompt (stored prompt injection)",
"location": "fleet_platform/services/embedding_svc.py:510-518 (chunking 91-118)",
"evidence": "format_retrieved_chunks appends c['chunk_text'] verbatim; chunk_playbook indexes raw YAML names/hosts/tasks without sanitization",
"impact": "Playbook/Salt content reaches the system prompt unsanitized. A crafted chunk (e.g. starting with '## Rules') can displace the grounding-rules tail used by _truncate_system_prompt, achieving stored injection on any later fleet query.",
"recommendation": "Apply sanitize_untrusted before embedding and before format_retrieved_chunks; neutralize code fences, '## Rules' headers, and model-control tokens in indexed content.",
"labels": ["security"],
},
{
"id": "AI-5", "persona": "Principal AI/LLM Expert", "severity": "High",
"title": "Cloud cost cap is in-process only, not shared across workers",
"location": "fleet_platform/services/cost_tracker.py:60-62",
"evidence": "STATE = _CostState() module-level singleton; no Redis/DB, no lock; _spend_usd += cost",
"impact": "With N worker processes the effective daily cap is N × DAILY_CAP_USD ($5 cap × 4 workers = $20/day). The += is also a data race under threading.",
"recommendation": "Move cost state to a shared atomic store (Redis INCRBYFLOAT or a DB row); until then document the cap as per-worker and size accordingly.",
"labels": ["bug"],
},
{
"id": "AI-6", "persona": "Principal AI/LLM Expert", "severity": "Medium",
"title": "Salt state name argument is LLM-controlled with no allowlist",
"location": "fleet_platform/agent/tools.py:282-287, 369-373",
"evidence": "state.apply <state> with `state` a free string (maxLength 200), no allowlist; run_salt_cmd allowlists function but apply_salt_state* does not constrain state names",
"impact": "The LLM (or an injection) can invoke arbitrary state names on minions; path-traversal-style names may be accepted depending on Salt file_roots.",
"recommendation": "Allowlist permitted state names (from platform settings) or validate against ^[a-zA-Z0-9_][a-zA-Z0-9_./-]{0,199}$.",
"labels": ["security"],
},
{
"id": "AI-7", "persona": "Principal AI/LLM Expert", "severity": "Medium",
"title": "run_salt_cmd passes LLM-controlled args list to Salt with no constraints",
"location": "fleet_platform/agent/tools.py:253-279",
"evidence": "args schema = {type: array} with no maxItems / item type / length; passed as-is to _run_salt_api",
"impact": "Information disclosure via Salt grain/pillar probes (e.g. grains.get with sensitive keys) directed by the LLM, surfacing in tool-result observations.",
"recommendation": "Add maxItems and per-item maxLength; allowlist safe grain keys; block pillar-accessing argument patterns.",
"labels": ["security"],
},
{
"id": "AI-8", "persona": "Principal AI/LLM Expert", "severity": "Medium",
"title": "Guard list references unregistered tool and omits a registered write-live tool",
"location": "fleet_platform/agent/guards.py:18-24",
"evidence": "_DEPLANING_TOOLS includes 'disable_node' (no ToolSpec) but omits 'enable_node' (registered as write_live)",
"impact": "The protected-node guard never fires for disable_node (no such tool) and does NOT protect enable_node — a deferred security hazard that looks covered but isn't.",
"recommendation": "Add enable_node to _DEPLANING_TOOLS now; add disable_node only when registered; add a test asserting every approval-required write_live tool is in _DEPLANING_TOOLS.",
"labels": ["security", "test"],
},
{
"id": "AI-9", "persona": "Principal AI/LLM Expert", "severity": "Medium",
"title": "Intent classifier is order-sensitive and has cross-intent false positives",
"location": "fleet_platform/services/llm_intent.py:58-69",
"evidence": "Rules ordered salt_state→ansible_playbook→...; bare word 'ansible' triggers ansible_playbook so 'explain my ansible playbook' misroutes; generation addendums say 'generate production-ready' vs fleet_query 'do not speculate'",
"impact": "Wrong task addendum is silently delivered, changing model behavior — generating executable content when a query was intended, or vice versa. No confidence/ambiguity handling.",
"recommendation": "Anchor patterns to avoid cross-intent matches, reorder so explain wins over generation when both match, and add confidence thresholding with fleet_query default.",
"labels": ["bug"],
},
{
"id": "AI-10", "persona": "Principal AI/LLM Expert", "severity": "Medium",
"title": "Cost tracked only when routed_via ends with 'cloud'; direct-endpoint runs untracked",
"location": "fleet_platform/api/routes/agent.py:183-186",
"evidence": "if routed_via and routed_via.endswith('cloud'): cost_tracker.record_tokens(...); routed_via is None for direct endpoint_id selection",
"impact": "Selecting a paid cloud endpoint directly by UUID records no spend and bypasses the daily cap; a different routing tag convention would also miss tracking.",
"recommendation": "Track cost based on endpoint.provider membership in a cloud-provider set, decoupled from routing-tag strings.",
"labels": ["bug"],
},
{
"id": "AI-11", "persona": "Principal AI/LLM Expert", "severity": "Medium",
"title": "Read-only Salt tools accept comma lists and silently broadcast to many minions",
"location": "fleet_platform/workers/salt_tasks.py:104-114; agent/tools.py (run_salt_cmd, apply_salt_state_dry_run)",
"evidence": "payload tgt_type='list' with target from minion_id (free string maxLength 255); _target_count comma check only applies to live approval-gated tools",
"impact": "run_salt_cmd / dry-run can be broadcast to many minions with no user indication (e.g. grains.items × 100 nodes), a large Salt-master load spike logged as a single tool call.",
"recommendation": "Reject commas in minion_id for read tools (single minion only) or use tgt_type='glob' with an exact match.",
"labels": ["security", "bug"],
},
{
"id": "AI-12", "persona": "Principal AI/LLM Expert", "severity": "Medium",
"title": "Audit _redact is length-only; secret tool arguments logged in plaintext",
"location": "fleet_platform/agent/audit.py:51-58",
"evidence": "_redact only truncates strings >500 chars; set_pillar 'value' (maxLength 2000) and YAML 'content' pass through into audit_events",
"impact": "Plaintext secrets (e.g. set_pillar value='db_password_new123') land in the audit table; anyone with DB/log access can read them.",
"recommendation": "Add a field-name blocklist ({value, content, password, secret, token, api_key} → [REDACTED]) or mark sensitive ToolSpec params for unconditional redaction.",
"labels": ["security"],
},
{
"id": "AI-13", "persona": "Principal AI/LLM Expert", "severity": "Low",
"title": "LLM final answer streamed to the browser without output sanitization",
"location": "fleet_platform/api/routes/agent.py:170",
"evidence": "yield _sse({'type': event.type, **event.data}); for 'final', event.data['text'] is raw LLM output",
"impact": "If the frontend renders final.text as Markdown/HTML unsafely, an LLM-generated (or injection-induced) script payload could execute in the operator's session.",
"recommendation": "Sanitize HTML at the API boundary before emitting final, enforce CSP, and audit the frontend renderer for unsafe HTML.",
"labels": ["security", "frontend"],
},
]
FINDINGS += [
{
"id": "UX-1", "persona": "Principal UI/UX Engineer", "severity": "Critical",
"title": "JWT token exposed as a WebSocket URL query parameter",
"location": "frontend/src/components/WebSSHTerminal.tsx:52; components/VNCViewer.tsx:34; components/ssh/MultiSessionTerminal.tsx:76",
"evidence": "const wsUrl = `ws://${window.location.host}/api/v1/ssh/session/${nodeId}?token=${encodeURIComponent(token)}`",
"impact": "The full JWT appears in the URL, which is logged by nginx/proxies, browser history, the address bar, and Referer headers. Anyone with log access can harvest valid session tokens.",
"recommendation": "Send the token as the first WS message after connect, or use a short-lived ticket from a pre-auth REST call. Fix all three components together.",
"labels": ["security", "frontend"],
},
{
"id": "UX-2", "persona": "Principal UI/UX Engineer", "severity": "Critical",
"title": "WebSocket hardcodes ws:// and silently breaks on HTTPS",
"location": "frontend/src/components/WebSSHTerminal.tsx:52; components/VNCViewer.tsx:34; components/ssh/MultiSessionTerminal.tsx:76",
"evidence": "const wsUrl = `ws://${window.location.host}/...`",
"impact": "On HTTPS deployments, mixed-content policy blocks ws:// silently; SSH and VNC are non-functional over HTTPS with no user-visible error.",
"recommendation": "Derive scheme: `${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}/...`",
"labels": ["bug", "frontend"],
},
{
"id": "UX-3", "persona": "Principal UI/UX Engineer", "severity": "Critical",
"title": "No React ErrorBoundary anywhere in the application",
"location": "frontend/src/App.tsx:132-186; components/Layout/Layout.tsx:93-95",
"evidence": "Suspense wraps <Outlet/> but ErrorBoundary has 0 results across src/",
"impact": "Any uncaught render error (null-deref on API data, bad cast, library exception) unmounts the whole app to a blank white screen with no recovery path, across all 20+ lazy routes.",
"recommendation": "Wrap <Outlet/> in an ErrorBoundary with a user-facing error card + Reload, and add a root-level catch-all boundary.",
"labels": ["bug", "frontend"],
},
{
"id": "UX-4", "persona": "Principal UI/UX Engineer", "severity": "High",
"title": "Auth tokens stored in localStorage (XSS token theft)",
"location": "frontend/src/api/client.ts:34,51-52; stores/authStore.ts:30-32",
"evidence": "localStorage.getItem('access_token'); localStorage.removeItem('access_token'/'refresh_token')",
"impact": "Any XSS gives an attacker both tokens — access for immediate calls and refresh for indefinite persistence — since localStorage is readable by any JS on the origin.",
"recommendation": "Move to httpOnly; Secure; SameSite=Strict cookies managed by the backend; at minimum keep only an in-memory access token and the refresh token in an httpOnly cookie.",
"labels": ["security", "frontend"],
},
{
"id": "UX-5", "persona": "Principal UI/UX Engineer", "severity": "High",
"title": "NodeDetail.tsx is a 2,454-line god component with 50+ useState and zero memoization",
"location": "frontend/src/pages/NodeDetail.tsx (entire file)",
"evidence": "50+ useState (157-210), 15+ useQuery, 10+ useMutation; useMemo=0, useCallback=0; derived sorts/filters recompute every render (1652, 2270, 262)",
"impact": "Every state change re-runs all derived computations and reconciles the entire tree, causing measurable jank on the process (250 rows) and SBOM (200 rows) tables. The component is untestable in isolation.",
"recommendation": "Split each tab into its own file (follow nodeDetail/IOSTabPanel.tsx) and wrap expensive derivations in useMemo.",
"labels": ["refactor", "frontend"],
},
{
"id": "UX-6", "persona": "Principal UI/UX Engineer", "severity": "High",
"title": "@tanstack/react-virtual installed but unused; large lists render full DOM",
"location": "frontend/package.json:17; pages/NodeDetail.tsx:248-253,295-302",
"evidence": "SBOM components per_page:200, processStats limit:250; grep useVirtualizer → no results",
"impact": "Up to 200 SBOM rows and 250 process rows mount as real DOM; the SBOM table alone is ~1,000 <td> nodes, causing slow render and scroll jank.",
"recommendation": "Apply the already-available useVirtualizer to both tables and move the SBOM text filter server-side (?name=).",
"labels": ["frontend", "refactor"],
},
{
"id": "UX-7", "persona": "Principal UI/UX Engineer", "severity": "High",
"title": "dangerouslySetInnerHTML with an unescaped fallback HTML literal for Ansible logs",
"location": "frontend/src/pages/BootstrapModal.tsx:707-715",
"evidence": "dangerouslySetInnerHTML={{__html: colorizeAnsibleLog(...) }} with an inline unescaped fallback '<span ...>(no output...)</span>'",
"impact": "colorizeAnsibleLog escapes today (mitigating XSS), but the pattern is fragile — a future change that forgets escaping reintroduces XSS. A safe <AnsiText> component already exists.",
"recommendation": "Replace with <AnsiText lines={...}/> and use a conditional JSX element for the fallback instead of an HTML literal.",
"labels": ["security", "frontend"],
},
{
"id": "UX-8", "persona": "Principal UI/UX Engineer", "severity": "High",
"title": "Modals lack a focus trap; Tab escapes to background content",
"location": "frontend/src/components/ConfirmDialog.tsx:22-26; pages/FleetDashboard.tsx (AddNodeModal); pages/NodeDetail.tsx (inline modals)",
"evidence": "ConfirmDialog has role='dialog' aria-modal='true' + Escape handler but no focus trap",
"impact": "Keyboard and screen-reader users can Tab into and trigger background controls while a modal is open; aria-modal declares but does not enforce the trap.",
"recommendation": "Use a focus-trapping hook or the native <dialog> element with built-in focus management.",
"labels": ["frontend", "ux"],
},
{
"id": "UX-9", "persona": "Principal UI/UX Engineer", "severity": "Medium",
"title": "Five concurrent 30s polling queries on the Dashboard page",
"location": "frontend/src/pages/DashboardPage.tsx:137-174",
"evidence": "fleet-overview, dashboard-nodes, security-dashboard, dashboard-drift + a live clock all at refetchInterval: 30_000",
"impact": "The most-visited page issues 5×N requests/30s across tabs with no cross-tab dedup, creating high DB query load.",
"recommendation": "Consolidate into a single /dashboard/summary endpoint, raise staleTime/refetchInterval to 60s, keep refetchOnWindowFocus:false.",
"labels": ["frontend", "refactor"],
},
{
"id": "UX-10", "persona": "Principal UI/UX Engineer", "severity": "Medium",
"title": "SecurityPage polls active SSH sessions every 10s (most aggressive interval)",
"location": "frontend/src/pages/SecurityPage.tsx:316-320",
"evidence": "useQuery(['ssh-sessions-active'], ... , { refetchInterval: 10_000 })",
"impact": "6 round-trips/min/tab; with many operators keeping the page open this is substantial sustained load.",
"recommendation": "Use a WebSocket subscription (consistent with WebSSH) or raise to 30s with refetchOnWindowFocus.",
"labels": ["frontend", "refactor"],
},
{
"id": "UX-11", "persona": "Principal UI/UX Engineer", "severity": "Medium",
"title": "All table headers missing scope=\"col\" (screen-reader inaccessibility)",
"location": "frontend/src/pages/NodeDetail.tsx (60+ <th>); FleetDashboard.tsx; SBOMExplorer.tsx; SaltMastersTab.tsx (codebase-wide)",
"evidence": "grep scope= → no results across src/",
"impact": "Screen readers cannot associate <th> with data cells in complex tables — WCAG 2.1 SC 1.3.1 (Level A) failure.",
"recommendation": "Add scope='col'/'row' to headers; extract a <DataTable> that enforces it by default.",
"labels": ["frontend", "ux"],
},
{
"id": "UX-12", "persona": "Principal UI/UX Engineer", "severity": "Medium",
"title": "Array index used as React key in multiple lists (incl. streaming chat)",
"location": "frontend/src/pages/NodeDetail.tsx:1413,1445,1477,1504,1533; components/LLMAssistant.tsx:505; SBOMExplorer.tsx:91; SettingsPage.tsx:1654,1837",
"evidence": "<tr key={i} ...>; <div key={i} ...> for streaming chat messages",
"impact": "On reorder/insert/delete React reuses DOM incorrectly — stale animations, wrong input state, visual glitches; the streaming chat list is especially vulnerable.",
"recommendation": "Use stable unique IDs (key={svc.service}, key={msg.id}); add an id to the chat message type.",
"labels": ["frontend"],
},
{
"id": "UX-13", "persona": "Principal UI/UX Engineer", "severity": "Medium",
"title": "Hardcoded Asia/Kolkata timezone for all users",
"location": "frontend/src/utils/time.ts:9; pages/DashboardPage.tsx:178; pages/NodeDetail.tsx:2221-2226",
"evidence": "timeZone: 'Asia/Kolkata' constants; NodeDetail duplicates inline toLocaleString instead of formatIST",
"impact": "All timestamps display in IST regardless of operator locale, impeding incident correlation; the inline duplication is a maintenance divergence.",
"recommendation": "Add a timezone preference in Settings (default Asia/Kolkata) and replace inline formatting with formatIST.",
"labels": ["frontend", "ux"],
},
{
"id": "UX-14", "persona": "Principal UI/UX Engineer", "severity": "Low",
"title": "Suspense has no error fallback for lazy route chunks (silent load failures)",
"location": "frontend/src/components/Layout/Layout.tsx:93-95",
"evidence": "<Suspense fallback={<RouteSpinner/>}><Outlet/></Suspense> with no ErrorBoundary",
"impact": "A failed lazy-chunk fetch (network/CDN miss, rolling deploy with new hashes) re-throws and, with no boundary, blanks the app.",
"recommendation": "Wrap Suspense in an ErrorBoundary with a 'Failed to load page — refresh' fallback (e.g. react-error-boundary).",
"labels": ["frontend"],
},
]
FINDINGS += [
{
"id": "TST-1", "persona": "Principal Tester", "severity": "Critical",
"title": "Agent run endpoint has zero integration or E2E coverage",
"location": "fleet_platform/api/routes/agent.py (no matching test)",
"evidence": "grep -r '/agent/run' tests/ → no matches; the SSE streaming endpoint wires AgentLoop/Executor/LLMPlanner/audit/session/tier_router with no end-to-end test",
"impact": "Any regression in session lifecycle, SSE encoding, or LLM endpoint wiring reaches production undetected.",
"recommendation": "Add an integration test using a mocked call_openai_compat: call POST /agent/run/stream via AsyncClient, assert SSE event shapes and that agent_sessions + llm_query_log rows are written.",
"labels": ["test"],
},
{
"id": "TST-2", "persona": "Principal Tester", "severity": "Critical",
"title": "Coverage gate excludes fleet_platform/agent/ entirely",
"location": ".github/workflows/ci.yml:205-211",
"evidence": "pytest --cov=fleet_platform/services --cov-fail-under=80; agent/ (loop, planner, executor, guards, tools, registry, audit) not measured; mutmut also only targets services/",
"impact": "The highest-risk logic (approval gates, co-sign threshold, guard hooks, loop limits) has no measured or enforced coverage floor.",
"recommendation": "Add --cov=fleet_platform/agent to the CI coverage command with its own fail-under (≈80%).",
"labels": ["test", "infra"],
},
{
"id": "TST-3", "persona": "Principal Tester", "severity": "High",
"title": "E2E suite has only 1 spec on master; 18+ live only in worktrees",
"location": "tests/e2e/ (only playbooks.spec.ts); playwright.config.ts:3",
"evidence": "tests/e2e/** = playbooks.spec.ts only; auth/nodes/drift/groups/fleet/bootstrap/audit/... specs exist unmerged in worktrees",
"impact": "Login/auth, node management, drift, groups, and audit trail have no E2E coverage on master; CI e2e runs effectively one spec.",
"recommendation": "Merge the worktree e2e specs after verifying they pass; prioritize auth.spec.ts and nodes.spec.ts.",
"labels": ["test"],
},
{
"id": "TST-4", "persona": "Principal Tester", "severity": "High",
"title": "Large fraction of unit tests scrape source strings instead of asserting behavior",
"location": "60+ files incl. tests/unit/test_toast_dismiss_timing.py; test_tasks_maintenance_fixes.py; test_rate_quota_715.py:68",
"evidence": "assert '\"error: 8000\"' in SRC; assert 'maintenance_mode' in segment; assert '@limiter.limit(\"6/minute\")' in src",
"impact": "Behavior-preserving refactors break these tests (false negatives), and broken behavior passes as long as the string remains (false confidence).",
"recommendation": "Replace source-scraping with behavioral tests (exercise endpoints/functions, inspect app.routes); keep AST tests only where AST is the sole reasonable option.",
"labels": ["test", "refactor"],
},
{
"id": "TST-5", "persona": "Principal Tester", "severity": "High",
"title": "Module-scoped integration DB session with no per-test rollback creates ordering dependencies",
"location": "tests/integration/conftest.py:39-44",
"evidence": "scope='module' db_session; await session.rollback() only at module teardown",
"impact": "Tests sharing a minion_id collide on unique constraints depending on order; --randomly-seed or partial runs cause false failures.",
"recommendation": "Wrap each test in begin_nested()/rollback (savepoint) or use function-scoped sessions.",
"labels": ["test"],
},
{
"id": "TST-6", "persona": "Principal Tester", "severity": "High",
"title": "Rate-limit tests assert structure, not behavior (limit could be disabled and pass)",
"location": "tests/unit/test_llm_rate_limit.py:6-27; test_rate_quota_715.py:62-69",
"evidence": "asserts limiter is imported and first param is request: Request; never checks the decorator is applied or that 429 is returned",
"impact": "Rate-limit bypass on the highest-cost LLM/agent endpoints would go undetected.",
"recommendation": "Add a burst integration test asserting 429, or inspect app.routes for the limit dependency.",
"labels": ["test"],
},
{
"id": "TST-7", "persona": "Principal Tester", "severity": "Medium",
"title": "time.sleep(0.01) for mtime ordering — flaky on low-resolution filesystems",
"location": "tests/unit/test_quarantine_write_713.py:63",
"evidence": "write_artifact(...); time.sleep(0.01); write_artifact(...); assert items[0]['filename']=='b.yml'",
"impact": "10ms is below ext4/HFS+ mtime resolution under load, so the 'newest first' assertion can flip intermittently in CI.",
"recommendation": "Backdate the first artifact with os.utime (as a sibling test already does) instead of relying on wall-clock progression.",
"labels": ["test"],
},
{
"id": "TST-8", "persona": "Principal Tester", "severity": "Medium",
"title": "Agent approval flow not tested over HTTP",
"location": "fleet_platform/services/agent_apply_svc.py; api/routes/agent.py",
"evidence": "Only test_agent_apply_svc_714.py (helpers); no test of POST /agent/apply/{id}/approve roundtrip, APPROVAL_TTL, co-sign bypass, or audit write",
"impact": "The primary safety gate for destructive agent actions has no end-to-end test.",
"recommendation": "Add an integration test: create a pending action, approve as admin, assert transition to approved and correct Celery dispatch.",
"labels": ["test"],
},
{
"id": "TST-9", "persona": "Principal Tester", "severity": "Medium",
"title": "Mutation testing has no CI enforcement and no workflow file",
"location": "docs/MUTATION_TESTING.md:53; .github/workflows/ (no mutation-tests.yml)",
"evidence": "Doc says mutation testing is intentionally not in CI and provides a workflow snippet that does not exist; mutmut configured but never enforced",
"impact": "Mutants can survive indefinitely; the coverage floor can be met by always-passing tests with no mechanism to catch it.",
"recommendation": "Add mutation-tests.yml (workflow_dispatch + weekly schedule), starting with cost_tracker.py and guards.py, reporting killed-rate.",
"labels": ["test", "infra"],
},
{
"id": "TST-10", "persona": "Principal Tester", "severity": "Medium",
"title": "pytest asyncio_default_fixture_loop_scope=function conflicts with module-scoped integration fixtures",
"location": "pytest.ini:3; tests/integration/conftest.py:12",
"evidence": "default loop scope = function, but all integration fixtures are scope='module', loop_scope='module'",
"impact": "New integration fixtures that forget loop_scope='module' silently get a per-test loop, causing 'attached to a different event loop' failures.",
"recommendation": "Set asyncio_default_fixture_loop_scope=module (or document the constraint prominently).",
"labels": ["test"],
},
{
"id": "TST-11", "persona": "Principal Tester", "severity": "Medium",
"title": "E2E PLAY-16 silently skips field assertions when API returns an empty array",
"location": "tests/e2e/playbooks.spec.ts:51-56",
"evidence": "if (body.length > 0) { expect(entry).toHaveProperty('filename'/'name'/'entry_type') }",
"impact": "If the playbooks dir is empty in the test env, all assertions are skipped and the test passes — the API contract is unenforced.",
"recommendation": "Seed a known playbook, drop the conditional, and assert body.length > 0 as a precondition.",
"labels": ["test"],
},
{
"id": "TST-12", "persona": "Principal Tester", "severity": "Medium",
"title": "Property tests limited to one file despite Hypothesis being installed and used historically",
"location": "pyproject.toml:63; tests/unit/test_playbook_discovery_hypothesis.py",
"evidence": ".hypothesis/constants/ has 100+ cached examples but only playbook discovery uses @given; sanitize_untrusted/validate_args/parse_nc_reachability have none",
"impact": "Fixed fuzz corpora go stale; prompt-injection sanitization in particular warrants property tests.",
"recommendation": "Add @given(st.text()) property tests for sanitize_untrusted and validate_args.",
"labels": ["test"],
},
{
"id": "TST-13", "persona": "Principal Tester", "severity": "Medium",
"title": "Worker maintenance/celery tasks tested only via source-scraping, not behavior",
"location": "tests/unit/test_tasks_maintenance_fixes.py:6-29; test_celery_app.py",
"evidence": "reads maintenance.py as a string and asserts substrings; never invokes mark_stale_nodes/reap_pending_actions/rotate_llm_query_logs",
"impact": "Logic errors (wrong SQL filter/threshold/status) in maintenance tasks are not caught by CI.",
"recommendation": "Call the tasks with a mocked db and assert the correct UPDATE parameters/behavior.",
"labels": ["test"],
},
{
"id": "TST-14", "persona": "Principal Tester", "severity": "Medium",
"title": "Only 7 integration test files on master vs 40+ unmerged in worktrees",
"location": "tests/integration/ (7 files); .claude/worktrees/*/tests/integration/ (40+)",
"evidence": "master lacks test_auth_endpoints/test_rbac_matrix/test_nodes_api/test_drift_api/test_llm_api/... which exist in worktrees",
"impact": "RBAC matrix, auth endpoints, node lifecycle, and the LLM API route have no integration coverage on master; the CI integration job runs a near-empty set.",
"recommendation": "Cherry-pick and merge the worktree integration tests that pass on current master.",
"labels": ["test"],
},
{
"id": "TST-15", "persona": "Principal Tester", "severity": "Low",
"title": "No contract/schema tests for OpenAPI response shapes",
"location": "fleet_platform/api/main.py; tests/integration/ (no schemathesis/openapi validator)",
"evidence": "No schemathesis/openapi-schema-validator; integration tests check ad-hoc field names but not full schema/spec conformance",
"impact": "Response drift from the declared Pydantic/OpenAPI schema can reach consumers (frontend, integrations) with no CI gate.",
"recommendation": "Validate /openapi.json with jsonschema, or add schemathesis (st.from_app(app)) over a subset of routes.",
"labels": ["test"],
},
]
FINDINGS += [
{
"id": "USR-1", "persona": "Common User", "severity": "Critical",
"title": "Salt-master silently absent from the Docker Compose stack",
"location": "deploy/docker-compose.yml:263-266; README.md:137,143",
"evidence": "compose comment: '# salt-master removed from Docker — runs natively on mm1'; README says 'Start the full stack (... salt-master ...)' and 'can run inside Docker'",
"impact": "A new user runs docker compose up expecting a working salt-master and gets none. Key acceptance, state runs, and drift all fail; the stack appears healthy but core fleet features are dead on arrival.",
"recommendation": "Remove salt-master from the Quick Start comment and the 'inside Docker' note; add a prerequisite explaining SALT_API_URL must point to an external master and link the setup playbook.",
"labels": ["docs", "bug"],
},
{
"id": "USR-2", "persona": "Common User", "severity": "Critical",
"title": "LICENSE file is missing (badge and link 404)",
"location": "README.md:8,270",
"evidence": "License badge → LICENSE and 'MIT — see LICENSE'; the LICENSE file does not exist in the repo",
"impact": "Legal/compliance evaluation hits a 404; downstream packages have no authoritative license; GitHub shows no license on the repo card.",
"recommendation": "Add an MIT LICENSE file at the repo root.",
"labels": ["docs"],
},
{
"id": "USR-3", "persona": "Common User", "severity": "High",
"title": "npm ci fails — frontend is managed with pnpm",
"location": "README.md:192; CONTRIBUTING.md:38",
"evidence": "Docs say 'cd frontend && npm ci'; package.json declares packageManager pnpm@10.29.3 and only pnpm-lock.yaml exists",
"impact": "Every new contributor and any CI step following the docs fails at install with 'npm ci requires an existing package-lock.json' before writing any code.",
"recommendation": "Replace npm ci with pnpm install --frozen-lockfile and add pnpm to prerequisites.",
"labels": ["docs"],
},
{
"id": "USR-4", "persona": "Common User", "severity": "High",
"title": "Hardcoded developer home paths as docker-compose volume defaults",
"location": "deploy/docker-compose.yml:150,194,197,244,247",
"evidence": "${PULSE_REPOS_DIR:-/home/dk/Documents/git/pulse}; ${PLAYBOOKS_FILES_DIR:-/home/dk/Documents/git/kri/playbooks/files}",
"impact": "On any other machine Docker creates empty dirs or workers crash on permissions; Ansible runs silently find no playbooks, with no indication the user must set these vars.",
"recommendation": "Move both vars into .env.docker.example with documented required values; remove developer-path defaults from compose.",
"labels": ["docs", "infra"],
},
{
"id": "USR-5", "persona": "Common User", "severity": "High",
"title": "CONTRIBUTING.md references scripts/kri.sh which does not exist",
"location": "CONTRIBUTING.md:58,61,64,67,152",
"evidence": "./scripts/kri.sh start/stop/status/logs; actual file is scripts/kri (no .sh)",
"impact": "A new contributor following local-stack setup immediately hits 'No such file or directory'.",
"recommendation": "Replace all ./scripts/kri.sh with ./scripts/kri.",
"labels": ["docs"],
},
{
"id": "USR-6", "persona": "Common User", "severity": "High",
"title": "CONTRIBUTING.md references a non-existent env file",
"location": "CONTRIBUTING.md:41",
"evidence": "cp deploy/.env.example deploy/.env; that file does not exist (template is .env.docker.example at repo root)",
"impact": "New contributors fail at env setup with 'cannot stat deploy/.env.example' before starting the stack.",
"recommendation": "Correct to cp .env.docker.example .env.docker and update later references.",
"labels": ["docs"],
},
{
"id": "USR-7", "persona": "Common User", "severity": "High",
"title": "Salt HTTP API required for all Salt ops but its setup is undocumented",
"location": ".env.docker.example:44-51; docs/salt-onboarding.md",
"evidence": "env comments say workers dispatch via salt-api and to add rest_cherrypy; the 14-step onboarding guide never mentions configuring it; SALT_API_USER/PASSWORD are CHANGE_ME placeholders",
"impact": "Even users who follow the full onboarding guide get workers that cannot dispatch any Salt command — drift/state/key ops silently fail, hinted at only by an env-file comment.",
"recommendation": "Add an onboarding step for Salt HTTP API setup (rest_cherrypy, API user, the three SALT_API_* vars).",
"labels": ["docs"],
},
{
"id": "USR-8", "persona": "Common User", "severity": "High",
"title": "Admin credentials inconsistent across docs",
"location": "README.md:141 vs docs/salt-onboarding.md:194",
"evidence": "README: admin/admin; onboarding curl: admin@fleet.local / changeme123",
"impact": "A user following onboarding to get a token uses changeme123 against an install seeded with admin and gets 401, with no way to know which doc is right.",
"recommendation": "Standardize on one set of defaults (or a placeholder) and make both docs match what the seed creates.",
"labels": ["docs"],
},
{
"id": "USR-9", "persona": "Common User", "severity": "High",
"title": "No forced password change for the admin/admin default",
"location": "README.md:141",
"evidence": "'change this immediately under Settings' is advisory only; no first-login enforcement",
"impact": "A distracted operator leaves the control plane (SSH keys, node secrets, playbook execution) behind a universal default with zero UX friction preventing it.",
"recommendation": "Force a password change on first login, or show a persistent banner until the default is changed.",
"labels": ["security", "ux"],
},
{
"id": "USR-10", "persona": "Common User", "severity": "Medium",
"title": "Onboarding Step 14 (manual Celery start) conflicts with Docker Compose path",
"location": "docs/salt-onboarding.md:449-488",
"evidence": "Step 14 manually launches four Celery processes; compose already defines worker/worker-ansible/beat; no guidance on which to follow",
"impact": "A Compose user runs redundant competing Celery processes (risking double execution) or is confused about whether Compose already handles it.",
"recommendation": "Split the guide into Docker-Compose and bare-metal paths; mark Step 14 bare-metal only.",
"labels": ["docs"],
},
{
"id": "USR-11", "persona": "Common User", "severity": "Medium",
"title": "Hardcoded developer personal path inside documentation",
"location": "docs/salt-onboarding.md:454",
"evidence": "cd /home/dk/Documents/git/kri inside a Step 14 code block",
"impact": "A reader copy-pasting hits 'No such file or directory', eroding trust in the docs.",
"recommendation": "Replace with cd /path/to/kri or a $KRI_ROOT variable.",
"labels": ["docs"],
},
{
"id": "USR-12", "persona": "Common User", "severity": "Medium",
"title": "Coverage floor contradicts itself across three documents",
"location": "README.md:119; CONTRIBUTING.md:163; TESTING.md:46",
"evidence": "README says 80%; CONTRIBUTING.md and TESTING.md say 75%",
"impact": "Contributors can't tell which number CI enforces, leading to confusion or wasted effort.",
"recommendation": "Pick one number, verify what ci.yml enforces, and align all three docs.",
"labels": ["docs"],
},
{
"id": "USR-13", "persona": "Common User", "severity": "Low",
"title": "Python version requirement contradicts itself",
"location": "README.md:9 (badge) vs CONTRIBUTING.md:22",
"evidence": "Badge: Python 3.13; CONTRIBUTING prerequisites: Python 3.11+",
"impact": "A contributor installs 3.11 then may hit 3.13-only syntax at import time, or installs 3.13 unnecessarily.",
"recommendation": "Align to a single minimum version across the badge and CONTRIBUTING.",
"labels": ["docs"],
},
]
# MARKER
