apiVersion: v1
kind: Service
metadata:
  name: kri-api
  namespace: kri
  labels:
    app: kri-api
    component: api
spec:
  selector:
    app: kri-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
