apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kri
  namespace: kri
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: kri.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kri-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kri-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - kri.local
